services:
  redis:
    image: docker.io/library/redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: unless-stopped

  redisinsight:
    image: docker.io/redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis-data:
  redisinsight-data:
